server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: payment-group
      enable-auto-commit: false
      auto-offset-reset: earliest

    listener:
      ack-mode: manual_immediate

    properties:
      max.poll.interval.ms: 120000
      max.poll.records: 1
      session.timeout.ms: 10000
      heartbeat.interval.ms: 3000