server:
  port: 8082

spring:
  kafka:
    consumer:
      group-id: payment-group
      enable-auto-commit: false
      auto-offset-reset: earliest
    listener:
      ack-mode: manual_immediate

    properties:
      session.timeout.ms: 10000
      heartbeat.interval.ms: 3000
      max.poll.interval.ms: 10000
      max.poll.records: 1